### ISSUE TITLE
scrolling zone is not working

### ISSUE THREAD

**Issue by apple890493** [TechStark/react-dnd-scrolling#22]
Hi ! I am new fresh in react.

<img width="719" alt="Screenshot 2023-01-05 at 2 00 14 PM" src="https://user-images.githubusercontent.com/46785951/210712226-f0ea30bf-6f2d-4ad5-adb3-7c91c6ce5616.png">

According to docs, I put the same code on my project, but if I want to trigger auto-scrolling still have to mouse over to the bottom or top of the container the first time.

I expected when closer to the top/bottom for 500px would trigger auto-scrolling immediately.

Has anyone had been same issues before? 🙏 Thanks

**Comment by azerum** [comment]
I am having the same problem with `react-dnd` `16.0.1`, `react-dnd-scrolling` `1.3.0` and `react` `18.2.0`

The `verticalStrength` and `horizontalStrength` properties don't seem to do anything. I've also tried to set `strengthMultiplier` to a very big value, and then to a negative value. Neither values changed the behavior of scroll in any way

The same is true if you pass the options to `useDndScrolling`, instead of using `withScrolling`

**Comment by ttt43ttt** [comment]
This should be fixed now. @apple890493  @azerum

**Comment by bgeffrault** [comment]
Hi, I got the same issue. I upgraded to v.1.3.3 and it's solved. Thank's.
Don't forget to update the demo with the latest version so, because it's still on 1.3.2 (the one with the issue)
